image: Visual Studio 2017
skip_tags: true
branches:
  only:
    - master
install:
  - git submodule update --init --recursive
  - nuget restore Client.sln
configuration: Release
build:
  project: Client.sln
after_build:
  - 7z a PMDShift.zip %APPVEYOR_BUILD_FOLDER%\Client\bin\Release\*
artifacts:
  - path: PMDShift.zip
    name: PMDShift
deploy:
  release: v$(appveyor_build_version)
  description: 'Release'
  provider: GitHub
  auth_token: $(github_release_token)
  artifact: PMDShift
  draft: false
  prerelease: false